package com.example.webengbigproject.Utilities;

import com.example.webengbigproject.OpenTDB.OpenTriviaDBQuestion;
import com.example.webengbigproject.OpenTDB.OpenTriviaDBResponse;

import java.util.ArrayList;

public class FactGenerator
{

    // TODO: Add datamuse and movie db to this; randomize it
    public static ArrayList<Fact> generateFacts(OpenTriviaDBResponse openTrivia)
    {
        ArrayList<OpenTriviaDBQuestion> openTDBQuestions = openTrivia.getResults();
        ArrayList<Fact> facts = new ArrayList<Fact>();
        Fact fact;

        // We will iterate over all the questions generated by opentriviaDB query and add them.
        for ( OpenTriviaDBQuestion eachQuestion : openTDBQuestions)
        {
            fact = new Fact();
            String q = eachQuestion.getQuestion();
            q = Character.toLowerCase(q.charAt(0)) + q.substring(1);

            if(!q.substring(q.length()-1).equals("?"))
            {
                q = q.substring(q.length()-2) + ":";
            }
            fact._fact = "Did you know " + q + " " + eachQuestion.getCorrectAnswer() + "!";

            facts.add(fact);
        }

        return facts;
    }
}
